### ISSUE TITLE
adding a mirror

### ISSUE THREAD

**Issue by asdfljdasflkjwfd** [mirror/mirror#23]
I would like to add a mirror for libosinfo. Can you give me access to transfer https://github.com/asdfljdasflkjwfd/libosinfo to mirror? Thanks.

**Comment by john-peterson** [comment]
what does it say when u try to transfer it? i assume it would ask me to approve the transfer

**Comment by asdfljdasflkjwfd** [comment]
"You don’t have admin rights to mirror"

**Comment by john-peterson** [comment]
try again. "Members can now create repositories."

**Comment by asdfljdasflkjwfd** [comment]
It went through this time. Thanks!

**Comment by asdfljdasflkjwfd** [comment]
It looks like I don't have write access to https://github.com/mirror/libosinfo

**Comment by john-peterson** [comment]
u have 
![image](https://cloud.githubusercontent.com/assets/207571/11167895/657598c6-8b76-11e5-8c3e-a6845673b04a.png)

**Comment by john-peterson** [comment]
i changed it to admin

**Comment by asdfljdasflkjwfd** [comment]
Thanks it's working.
