### ISSUE TITLE
Remove mirror/chromium 

### ISSUE THREAD

**Issue by john-peterson** [mirror/mirror#3]
remove [mirror/chromium](https://github.com/mirror/chromium) because
- GitHub mirror chromium to [mirrors/chromium](https://github.com/mirrors/chromium)
- no information loss: no information is lost because mirror/chromium don't contain metatada ([pulls](https://github.com/mirror/chromium/pulls), [issues](https://github.com/mirror/chromium/issues) and [wiki](https://github.com/mirror/chromium/wiki) is empty)
- pulls and issues equally welcome: pull requests and issues are equally welcome at [mirrors/chromium](https://github.com/mirrors/chromium) as at [mirror/chromium](https://github.com/mirror/chromium)
- duplication: it's less duplication to have 1 (rather than more than 1) chromium GitHub mirror
- update frequency: mirrors update more often (>1 time / 24 h) than mirror (1 time / 24 h)
- chromium git repo changed: mirrors/chromium mirror https://chromium.googlesource.com/chromium/src that has different hashes from and has superseded http://git.chromium.org/chromium/chromium.git that mirror/chromium mirror
- the mirror/chromium watchers, stargazers and members can use mirrors/chromium instead
  - [watchers](https://github.com/mirror/chromium/watchers): 9
  - [stargazers](https://github.com/mirror/chromium/stargazers): 20
  - [members](https://github.com/mirror/chromium/network/members): 9

**Comment by john-peterson** [comment]
add https://chromium.googlesource.com/chromium/src because there's no chromium mirror in github

**Comment by john-peterson** [comment]
paul irish suggested this

Hi John!

Thanks very much for putting up https://github.com/mirror/chromium and making sure it's updated. Very kind of you... most people hate using the real chromium git repo. :)

In the meantime, Github runs this unofficial mirror: https://github.com/mirrors/chromium  

For our purposes it makes more sense to have only that one. Are you okay with deleting your repo?

Thanks very much

_
Paul Irish
Chrome Developer Advocate

**Comment by jkldgoefgkljefogeg** [comment]
https://github.com/mirrors/chromium has stopped updating a while back, do you mind me resuming this mirror?

**Comment by john-peterson** [comment]
👍





On Thu, Jan 14, 2016 at 10:22 AM -0800, "kjeojfeofjgeofkjodfioejo" <notifications@github.com> wrote:





https://github.com/mirrors/chromium has stopped updating a while back, do you mind me resuming this mirror?

---
